# Generated by Django 4.2.3 on 2023-07-26 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='f_fabricación',
            new_name='f_fabricacion',
        ),
    ]
