# Generated by Django 4.2.3 on 2023-07-26 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0002_rename_f_fabricación_producto_f_fabricacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='director_general',
            name='especialidad',
            field=models.CharField(default='laboratorio', max_length=40),
        ),
        migrations.AddField(
            model_name='laboratorio',
            name='ciudad',
            field=models.CharField(default='Santiago', max_length=40),
        ),
        migrations.AddField(
            model_name='laboratorio',
            name='pais',
            field=models.CharField(default='Chile', max_length=40),
        ),
    ]
